build:
    tests:
        override:
            -
                command: phpunit --bootstrap ./tests/bootstrap.php --configuration ./tests/phpunit.xml --colors
                coverage:
                    file: my-coverage-file
                    format: php-clover