build:
    tests:
        override:
            -
                command: phpunit --coverage-clover=/build/logs/clover.xml
                coverage:
                    file: my-coverage-file
                    format: php-clover