build:
    tests:
        override:
            -
                command: phpunit --bootstrap ./tests/bootstrap.php --configuration ./tests/phpunit.xml --colors
                coverage:
                    file: /logs/clover.xml
                    format: php-clover