<?php

namespace SimpleORM;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-12-05 at 16:25:11.
 */
class AbstractDataMapperTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var AbstractDataMapper
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		//$this->object = new AbstractDataMapper;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * @covers SimpleORM\AbstractDataMapper::getEntityTable
	 * @todo   Implement testGetEntityTable().
	 */
	public function testGetEntityTable()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\AbstractDataMapper::getAdapter
	 * @todo   Implement testGetAdapter().
	 */
	public function testGetAdapter()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\AbstractDataMapper::findById
	 * @todo   Implement testFindById().
	 */
	public function testFindById()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\AbstractDataMapper::save
	 * @todo   Implement testSave().
	 */
	public function testSave()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\AbstractDataMapper::findBySpecification
	 * @todo   Implement testFindBySpecification().
	 */
	public function testFindBySpecification()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\AbstractDataMapper::delete
	 * @todo   Implement testDelete().
	 */
	public function testDelete()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\AbstractDataMapper::findAllBySpecification
	 * @todo   Implement testFindAllBySpecification().
	 */
	public function testFindAllBySpecification()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\AbstractDataMapper::findAll
	 * @todo   Implement testFindAll().
	 */
	public function testFindAll()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\AbstractDataMapper::useJoins
	 * @todo   Implement testUseJoins().
	 */
	public function testUseJoins()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\AbstractDataMapper::withDelete
	 * @todo   Implement testWithDelete().
	 */
	public function testWithDelete()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}
}
