<?php

namespace SimpleORM;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-12-05 at 16:25:49.
 */
class SpecificationTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Specification
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Specification;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * @covers SimpleORM\Specification::getWhere
	 * @todo   Implement testGetWhere().
	 */
	public function testGetWhere()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\Specification::getLimit
	 * @todo   Implement testGetLimit().
	 */
	public function testGetLimit()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\Specification::getOfset
	 * @todo   Implement testGetOfset().
	 */
	public function testGetOfset()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\Specification::getJoins
	 * @todo   Implement testGetJoins().
	 */
	public function testGetJoins()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\Specification::getOrder
	 * @todo   Implement testGetOrder().
	 */
	public function testGetOrder()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\Specification::getManualJoins
	 * @todo   Implement testGetManualJoins().
	 */
	public function testGetManualJoins()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\Specification::getGroup
	 * @todo   Implement testGetGroup().
	 */
	public function testGetGroup()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\Specification::getManualWheres
	 * @todo   Implement testGetManualWheres().
	 */
	public function testGetManualWheres()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\Specification::getWhereType
	 * @todo   Implement testGetWhereType().
	 */
	public function testGetWhereType()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\Specification::setWhere
	 * @todo   Implement testSetWhere().
	 */
	public function testSetWhere()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\Specification::setLimit
	 * @todo   Implement testSetLimit().
	 */
	public function testSetLimit()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\Specification::setOfset
	 * @todo   Implement testSetOfset().
	 */
	public function testSetOfset()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\Specification::setJoins
	 * @todo   Implement testSetJoins().
	 */
	public function testSetJoins()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\Specification::setOrder
	 * @todo   Implement testSetOrder().
	 */
	public function testSetOrder()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\Specification::setManualJoins
	 * @todo   Implement testSetManualJoins().
	 */
	public function testSetManualJoins()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\Specification::setGroup
	 * @todo   Implement testSetGroup().
	 */
	public function testSetGroup()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\Specification::setManualWheres
	 * @todo   Implement testSetManualWheres().
	 */
	public function testSetManualWheres()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\Specification::setWhereType
	 * @todo   Implement testSetWhereType().
	 */
	public function testSetWhereType()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers SimpleORM\Specification::getCriteria
	 * @todo   Implement testGetCriteria().
	 */
	public function testGetCriteria()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}
}
